name: Angular CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test Angular in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            node:18-bullseye \
            /bin/bash -c "npm ci && npm run build -- --configuration=production && npm test -- --watch=false"
