name: docker pipeline

on:
  push:
    branches:
      - feat/setup
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20.18.0'

      - run: npm install
      - run: npm run build:prod
